apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config 
  namespace: dev
data:
  REDIS_HOST: "redis-dev-master"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-dev-postgresql"
  POSTGRES_PORT: "5432"