apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-dev-spc
  namespace: dev
spec:
  provider: azure
  secretObjects:                               
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: "POSTGRES-USER"
          key: "POSTGRES_USER"
        - objectName: "POSTGRES-PASSWORD"
          key: "POSTGRES_PASSWORD"
        - objectName: "POSTGRES-DB"
          key: "POSTGRES_DB"
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    useManagedIdentity: "true"
    keyvaultName: "kv-dev-ac26"
    tenantId: "5775cf82-35e6-4f8c-b604-fcb7a5abce7f"
    userAssignedIdentityID: "60f0cbb8-9b45-4498-aaa2-a013b1594bc6" #kubelet identity that runs the pod that asking for secrets
    #userAssignedIdentityID: "ae68d5a4-3364-4be0-9c90-bd418bebc84c"
    #userAssignedIdentityID: "da73538a-c287-41b0-85b1-f10631073731"
    userAssignedIdentityID: "d3e76b3a-da87-43cd-8b50-75494c4fe24a"
    objects: |
      array:
        - |
          objectName: "POSTGRES-USER"
          objectType: secret
        - |
          objectName: "POSTGRES-PASSWORD"
          objectType: secret
        - |
          objectName: "POSTGRES-DB"
          objectType: secret
