apiVersion: batch/v1
kind: Job
metadata:
  name: seed
  namespace: dev
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: tactfulacr.azurecr.io/devops-seed:latest
         # envFrom:
          #  - configMapRef:
          #      name: app-config
          #  - secretRef:
          #      name: app-secrets
          #volumeMounts:
          #  - name: kv-secrets
          #    mountPath: /mnt/secrets-store
          #    readOnly: true
      #volumes:
      #  - name: kv-secrets
      #    csi:
      #      driver: secrets-store.csi.k8s.io
      #      readOnly: true
      #      volumeAttributes:
      #        secretProviderClass: "kv-dev-spc"