apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-dev-spc
  namespace: dev
spec:
  provider: azure
  secretObjects:                               
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: "POSTGRES-USER"
          key: "POSTGRES_USER"
        - objectName: "POSTGRES-PASSWORD"
          key: "POSTGRES_PASSWORD"
        - objectName: "POSTGRES-DB"
          key: "POSTGRES_DB"
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "kv-dev-ac26"
    tenantId: "5775cf82-35e6-4f8c-b604-fcb7a5abce7f"
    objects: |
      array:
        - |
          objectName: "POSTGRES-USER"
          objectType: secret
        - |
          objectName: "POSTGRES-PASSWORD"
          objectType: secret
        - |
          objectName: "POSTGRES-DB"
          objectType: secret
